### ISSUE TITLE
triggerPair pattern in m2m.incr.viatra causes performance bottleneck

### ISSUE THREAD

**Issue by abelhegedus** [IncQueryLabs/incquery-examples-cps#35]
Based on both performance tests and query hotspot detection, the [triggerPair pattern](https://github.com/IncQueryLabs/incquery-examples-cps/blob/master/transformations/org.eclipse.incquery.examples.cps.xform.m2m.incr.viatra/src/org/eclipse/incquery/examples/cps/xform/m2m/incr/viatra/patterns/cpsXformM2M.eiq#L77) is the single biggest bottleneck for this variant.

**Comment by ujhelyiz** [comment]
The issue was fixed by splitting the pattern by reachability and everything else.
