### ISSUE TITLE
Fill in the copyright headers

### ISSUE THREAD

**Issue by ujhelyiz** [IncQueryLabs/incquery-examples-cps#68]
In order to [merge the CPS example to eclipse.org](https://bugs.eclipse.org/bugs/show_bug.cgi?id=490621) , we need to have copyright headers added.

@abelhegedus can you help in providing the information to add to the files (more specifically, in figuring out the algorithm to do it correctly with regards to all contributors)?

**Comment by ujhelyiz** [comment]
@tamasborbas can you add yourself to the copyright headers of the viatra test projects? It was basically done by you, and would help future work, if it would be set correctly.

**Comment by abelhegedus** [comment]
Fixed by #70
