### ISSUE TITLE
BatchSimple & BatchOptimized create incorrect state machines

### ISSUE THREAD

**Issue by fjouault** [IncQueryLabs/incquery-examples-cps#72]
Some BehaviorStates generated by these transformations have outgoing BehaviorTransitions that belong to a different DeploymentBehavior than the one owning the BehaviorState.

The following code checks that BehaviorStates and BehaviorTransitions do not target elements from a different DeploymentBehavior:

```
		for(trace : cps2dep.traces) {
//			assertEquals(1, trace.cpsElements.size)
			val sourceElement = trace.cpsElements.get(0)
			switch sourceElement {
				Transition: {
					for(targetElement : trace.deploymentElements) {
						println(targetElement.description)
						assertEquals("Transition targeting a state from a different state machine", targetElement.eContainer, (targetElement as BehaviorTransition).to.eContainer)
					}
				}
				State: {
					for(targetElement : trace.deploymentElements) {
						println(targetElement.description)
						for(targetTransition : (targetElement as BehaviorState).outgoing) {
							assertEquals("State targeting a transition from a different state machine", targetElement.eContainer, targetTransition.eContainer)
						}
					}
				}
			}
		}
```

This check could be performed in several places where state machines are generated.

It notably detects an issue with BatchSimple & BatchOptimized when performing it after the second call to executeTransformation of method ActionMappingTest.addHostInstanceOfSend. This issue seems to be caused by incorrect handling of trace information in these transformations.

**Comment by abelhegedus** [comment]
Thanks for the report, problem fixed in https://git.eclipse.org/c/viatra/org.eclipse.viatra.examples.git/commit/cps?id=f65fd3bccf25b0af1795d2e4f411ac1626c0ecb3
